#!/usr/bin/env bun
/**
 * Database initialization script for OpenKraken orchestrator
 * 
 * Creates storage directories and initializes the SQLite database schema
 * using platform-appropriate paths with WAL mode for better concurrency.
 */

import { resolve } from 'path';
import { mkdir, existsSync } from 'fs';
import { Database } from 'bun:sqlite';
import { getPlatformPaths, ensureDirectories } from '../src/platform/index';

const SCHEMA_VERSION = '001';

/**
 * Main initialization function
 */
async function initializeDatabase(): Promise<void> {
  console.log('=== OpenKraken Database Initialization ===\n');

  // Get platform-appropriate paths
  const paths = getPlatformPaths();
  const databasePath = `${paths.data}/openkraken.db`;

  console.log(`Platform: ${process.platform}`);
  console.log(`Data directory: ${paths.data}`);
  console.log(`Database path: ${databasePath}`);

  // Create directories with correct permissions
  console.log('\nEnsuring storage directories exist...');
  const dirResult = await ensureDirectories();
  
  if (dirResult.success) {
    console.log('Directories created successfully');
  } else {
    console.warn('Some directories could not be created:');
    dirResult.errors.forEach(err => console.warn(`  - ${err}`));
  }

  // Initialize database if it doesn't exist
  if (existsSync(databasePath)) {
    console.log('\nDatabase already exists. Verifying schema...');
    await verifySchema(databasePath);
  } else {
    console.log('\nCreating new database...');
    await createDatabase(databasePath);
  }

  console.log('\n=== Database initialization complete ===');
}

/**
 * Creates the database and initial schema
 */
async function createDatabase(databasePath: string): Promise<void> {
  console.log(`Creating database: ${databasePath}`);

  // Create database using bun:sqlite
  // This creates the actual .db file
  const db = new Database(databasePath);

  try {
    // Enable WAL mode for better concurrency
    // WAL (Write-Ahead Logging) allows concurrent reads while writing
    db.run("PRAGMA journal_mode = WAL");
    
    // Set synchronous mode to NORMAL for better performance while maintaining durability
    db.run("PRAGMA synchronous = NORMAL");
    
    // Enable foreign keys
    db.run("PRAGMA foreign_keys = ON");
    
    // Create all tables
    db.run(generateSchema());
    
    console.log('Database schema created successfully');
    console.log('WAL mode enabled for concurrent access');
  } finally {
    // Close the database connection
    db.close();
  }
}

/**
 * Verifies existing database schema
 */
async function verifySchema(databasePath: string): Promise<void> {
  console.log('Verifying database integrity...');
  
  const db = new Database(databasePath);
  
  try {
    // Check if WAL mode is enabled
    const journalMode = db.query("PRAGMA journal_mode").get() as { journal_mode: string };
    console.log(`Journal mode: ${journalMode.journal_mode}`);
    
    // Verify key tables exist
    const tables = db.query(`
      SELECT name FROM sqlite_master 
      WHERE type='table' AND name NOT LIKE 'sqlite_%'
      ORDER BY name
    `).all() as Array<{ name: string }>;
    
    console.log(`Tables found: ${tables.map(t => t.name).join(', ')}`);
    
    console.log('Database verified successfully');
  } finally {
    db.close();
  }
}

/**
 * Generates the database schema
 */
function generateSchema(): string {
  return `
-- OpenKraken Database Schema
-- Generated by init-db.ts

-- Schema version tracking table
CREATE TABLE IF NOT EXISTS schema_versions (
    version TEXT PRIMARY KEY,
    applied_at TEXT NOT NULL,
    checksum TEXT NOT NULL,
    description TEXT
);

-- Insert initial schema version
INSERT INTO schema_versions (version, applied_at, checksum, description)
VALUES (
    '${SCHEMA_VERSION}',
    datetime('now'),
    'pending',
    'Initial schema'
);

-- Thread tracking
CREATE TABLE IF NOT EXISTS threads (
    id TEXT PRIMARY KEY,
    metadata BLOB,
    created_at TEXT NOT NULL DEFAULT datetime('now'),
    updated_at TEXT NOT NULL DEFAULT datetime('now')
);

-- Message log with encryption support
CREATE TABLE IF NOT EXISTS messages (
    id TEXT PRIMARY KEY,
    thread_id TEXT NOT NULL,
    role TEXT NOT NULL,
    content BLOB NOT NULL,
    encrypted INTEGER DEFAULT 0,
    metadata BLOB,
    created_at TEXT NOT NULL DEFAULT datetime('now')
);

-- Semantic memory storage
CREATE TABLE IF NOT EXISTS memories (
    id TEXT PRIMARY KEY,
    content TEXT NOT NULL,
    embedding BLOB,
    metadata BLOB,
    importance REAL DEFAULT 0.5,
    created_at TEXT NOT NULL DEFAULT datetime('now'),
    updated_at TEXT NOT NULL DEFAULT datetime('now')
);

CREATE TABLE IF NOT EXISTS memories_embeddings (
    id TEXT PRIMARY KEY,
    memory_id TEXT NOT NULL,
    model TEXT NOT NULL,
    embedding BLOB NOT NULL,
    created_at TEXT NOT NULL DEFAULT datetime('now'),
    FOREIGN KEY (memory_id) REFERENCES memories(id)
);

-- Audit logging
CREATE TABLE IF NOT EXISTS audit_events (
    id TEXT PRIMARY KEY,
    event_type TEXT NOT NULL,
    actor TEXT,
    target TEXT,
    action TEXT,
    result TEXT,
    metadata BLOB,
    timestamp TEXT NOT NULL DEFAULT datetime('now')
);

-- Proxy/network access logs
CREATE TABLE IF NOT EXISTS proxy_logs (
    id TEXT PRIMARY KEY,
    url TEXT NOT NULL,
    method TEXT NOT NULL,
    request_headers BLOB,
    request_body BLOB,
    response_status INTEGER,
    response_headers BLOB,
    response_body BLOB,
    duration_ms INTEGER,
    error TEXT,
    timestamp TEXT NOT NULL DEFAULT datetime('now')
);

-- Skills metadata
CREATE TABLE IF NOT EXISTS skills (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    version TEXT NOT NULL,
    source TEXT NOT NULL,
    manifest BLOB NOT NULL,
    enabled INTEGER DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT datetime('now'),
    updated_at TEXT NOT NULL DEFAULT datetime('now')
);

-- Security analysis reports
CREATE TABLE IF NOT EXISTS skill_analysis_reports (
    id TEXT PRIMARY KEY,
    skill_id TEXT NOT NULL,
    analysis_type TEXT NOT NULL,
    findings BLOB NOT NULL,
    risk_level TEXT,
    reviewed_by TEXT,
    reviewed_at TEXT,
    approved INTEGER DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT datetime('now'),
    FOREIGN KEY (skill_id) REFERENCES skills(id)
);

-- Skill lifecycle audit log
CREATE TABLE IF NOT EXISTS skill_audit_log (
    id TEXT PRIMARY KEY,
    skill_id TEXT NOT NULL,
    action TEXT NOT NULL,
    actor TEXT,
    details BLOB,
    timestamp TEXT NOT NULL DEFAULT datetime('now'),
    FOREIGN KEY (skill_id) REFERENCES skills(id)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_messages_thread ON messages(thread_id);
CREATE INDEX IF NOT EXISTS idx_memories_embedding ON memories(embedding);
CREATE INDEX IF NOT EXISTS idx_audit_events_type ON audit_events(event_type);
CREATE INDEX IF NOT EXISTS idx_audit_events_timestamp ON audit_events(timestamp);
CREATE INDEX IF NOT EXISTS idx_proxy_logs_timestamp ON proxy_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_skills_name ON skills(name);
CREATE INDEX IF NOT EXISTS idx_skill_audit_log_skill ON skill_audit_log(skill_id);

-- Note: Checkpoint tables (checkpoints, writes) are created by bun-sqlite-checkpointer
-- via initializeSchema() when the checkpointer is initialized.
`;
}

// Run initialization
initializeDatabase()
  .then(() => {
    console.log('\nDatabase initialization successful');
    process.exit(0);
  })
  .catch((error) => {
    console.error('Database initialization failed:', error);
    process.exit(1);
  });
